//
// Created by Adrien COURNAND on 20/08/2022.
//
// The libc will not be compiled with the freestanding option, and I need to provide the stdin.h header. The one
// generated by gcc is perfectly fine and will be the one used.
//

#ifndef BEETLEOS_STDINT_H
#define BEETLEOS_STDINT_H

#include <stdint-gcc.h>

#endif //BEETLEOS_STDINT_H
